[INFO 18-02-01 18:22:53 coralogger:create_logger:24] Starting Logger: KubBuilder Log.
[INFO 18-02-01 18:22:53 start:<module>:14] Starting Flask App - KubBuilder
[DEBUG 18-02-01 18:22:53 start:<module>:15] Additional info about KubBuilder
[DEBUG 18-02-01 18:23:10 controller:index:26] index request: {'request_id': '57739371-8bd7-4ab9-b18a-3c34ceb35188', 'callback_url': 'https://botmanager-backend-dev.pype.tech//callbacks/kub_builder', 'executor_location': 'https://s3-us-west-2.amazonaws.com/pybots/DevBots/TourismBot/v1/nlu.zip', 'host_path': ['some', 'host']}
[DEBUG 18-02-01 18:23:10 controller:background:41] Start building! 57739371-8bd7-4ab9-b18a-3c34ceb35188
[DEBUG 18-02-01 18:23:10 controller:index:31] index response for: 57739371-8bd7-4ab9-b18a-3c34ceb35188, status code: 200, response: {'success': True}
[ERROR 18-02-01 18:23:11 controller:background:53] background error for: 57739371-8bd7-4ab9-b18a-3c34ceb35188, error_json: {'error': 'Traceback (most recent call last):\n  File "/home/admssa/git/KubBuilder/controller.py", line 42, in background\n    response_data = kubbuilder_service.run(contents[\'executor_location\'], contents[\'host_path\'])\n  File "/home/admssa/git/KubBuilder/kubbuilder_service.py", line 16, in run\n    download_unzip(executor_location)\n  File "/home/admssa/git/KubBuilder/kubbuilder_service.py", line 32, in download_unzip\n    constants.LOCAL_PATH)\n  File "/home/admssa/git/KubBuilder/operations/cloud_ops.py", line 18, in download_file\n    s3_client.Bucket(bucket_name).download_file(key_name,full_path)\n  File "/home/admssa/git/KubBuilder/venv/lib/python3.5/site-packages/boto3/s3/inject.py", line 168, in bucket_download_file\n    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)\n  File "/home/admssa/git/KubBuilder/venv/lib/python3.5/site-packages/boto3/s3/inject.py", line 130, in download_file\n    extra_args=ExtraArgs, callback=Callback)\n  File "/home/admssa/git/KubBuilder/venv/lib/python3.5/site-packages/boto3/s3/transfer.py", line 299, in download_file\n    future.result()\n  File "/home/admssa/git/KubBuilder/venv/lib/python3.5/site-packages/s3transfer/futures.py", line 73, in result\n    return self._coordinator.result()\n  File "/home/admssa/git/KubBuilder/venv/lib/python3.5/site-packages/s3transfer/futures.py", line 233, in result\n    raise self._exception\n  File "/home/admssa/git/KubBuilder/venv/lib/python3.5/site-packages/s3transfer/tasks.py", line 255, in _main\n    self._submit(transfer_future=transfer_future, **kwargs)\n  File "/home/admssa/git/KubBuilder/venv/lib/python3.5/site-packages/s3transfer/download.py", line 349, in _submit\n    **transfer_future.meta.call_args.extra_args\n  File "/home/admssa/git/KubBuilder/venv/lib/python3.5/site-packages/botocore/client.py", line 312, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File "/home/admssa/git/KubBuilder/venv/lib/python3.5/site-packages/botocore/client.py", line 605, in _make_api_call\n    raise error_class(parsed_response, operation_name)\nbotocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden\n'}
